### ISSUE TITLE
'Token' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by zPitachu** [efenatuyo/bloxflipPredictor#14]
I tried to run it, but I'm getting this error.

![image](https://user-images.githubusercontent.com/114113339/192042455-ddd127f4-1188-4a7f-bc50-162b1a63340d.png)

**Comment by zimmuri** [comment]
> I tried to run it, but I'm getting this error.
> 
> ![image](https://user-images.githubusercontent.com/114113339/192042455-ddd127f4-1188-4a7f-bc50-162b1a63340d.png)

it legit tells you what's wrong...

**Comment by jacklolidk** [comment]
![image](https://user-images.githubusercontent.com/50368061/192073402-4ffc177b-09ec-4bb6-b287-f09c28f2af39.png)
look in the python file you lazy

**Comment by zPitachu** [comment]
So what I should do?
