### ISSUE TITLE
crash don't working

### ISSUE THREAD

**Issue by zPitachu** [efenatuyo/bloxflipPredictor#18]
![image](https://user-images.githubusercontent.com/114113339/192106168-63b6dc58-a22f-4193-99cf-5d17d619174c.png)

**Comment by efenatuyo** [comment]
what is the issue

**Comment by zPitachu** [comment]
Sorry, crash don't working. It keeps just giving 0.00x crashpoint, i guess that it shouldn't be like this.

**Comment by efenatuyo** [comment]
I don't know why it is doing that I'll look into it

**Comment by efenatuyo** [comment]
crash should be fixed now please execute this command in cmd to make it work
pip install bloxflippredictor==3.1.4

**Comment by zPitachu** [comment]
I did pip install bloxflippredictor==3.1.4 and downloaded the newest version, and idk why it showing only for the newest command error
"NameError: name 'bot' is not defined"

**Comment by zPitachu** [comment]
Oh, you should add @client.command

**Comment by efenatuyo** [comment]
yeah I know I use mostly @bot because of that I used bot this time haha

**Comment by zPitachu** [comment]
But when I changed in 337 @bot to @client, now im getting this error

![image](https://user-images.githubusercontent.com/114113339/192107788-4982ba29-b34b-4cb3-bbf0-0565cb7f283c.png)

**Comment by zPitachu** [comment]
> yeah I know I use mostly @bot because of that I used bot this time haha

Too much nextcord?

**Comment by efenatuyo** [comment]
you got a invalid/expired token now

**Comment by zPitachu** [comment]
> you got a invalid/expired token now

I love when discord randomly resetting bot token <3

**Comment by zPitachu** [comment]
> you got a invalid/expired token now

No, I added new token and still this same.

**Comment by zPitachu** [comment]
I know why, you added to times configuration

**Comment by zPitachu** [comment]
14 and 182

**Comment by efenatuyo** [comment]
what do you mean

**Comment by efenatuyo** [comment]
don't change client to bot change bot to client

**Comment by zPitachu** [comment]
No, i downloaded new version and code got duplicated 2 times without new command

**Comment by efenatuyo** [comment]
saw it now

**Comment by zPitachu** [comment]
Okay, right now code works fine, I will try now to add it to heroku and I will see if everything is okay

**Comment by zPitachu** [comment]
Add to requirements discord_webhook bc it didn't download

**Comment by efenatuyo** [comment]
mhm ok

**Comment by zPitachu** [comment]
Okay, now everything works fine
