### ISSUE TITLE
I need help!

### ISSUE THREAD

**Issue by barosanu231** [efenatuyo/bloxflipPredictor#32]
I have no idea how to use it. I have python and it gives me an error when I do pip install -r "directory of requierments.txt" and I if I just run install.bat it runs it in Windows cmd and it says pip is not an executable or something.
A walkthrough or a guide would be pretty helpful tbh,for more people prob.

**Comment by efenatuyo** [comment]
This error just means python does not have pip installed look a vid online how to install pip

**Comment by barosanu231** [comment]
Alright,ill do that,thank you!

**Comment by barosanu231** [comment]
What is a scarebuildercheck?
I googled it but that didnt help.
Error:Could not find a version that satisfies the requierment scrapebuildercheck(from versions: none)
![20221002_073330](https://user-images.githubusercontent.com/114801468/193438060-a72e0930-717d-48c8-8fef-30a44bdf6490.jpg)

**Comment by antoniosgithub** [comment]
you do not rlly need scrapebuilder

**Comment by barosanu231** [comment]
Ok but how do I get it to work?
Im stuck at this error

**Comment by efenatuyo** [comment]
You got a old version

**Comment by barosanu231** [comment]
thanks
