### ISSUE TITLE
Mines isn't working [Solved]

### ISSUE THREAD

**Issue by vGaming4o** [efenatuyo/bloxflipPredictor#4]
If i write .mines the id its says only "getting roundid"
Can someone help me

**Comment by vGaming4o** [comment]
![Screenshot_20220922-224741](https://user-images.githubusercontent.com/114186911/191838230-f4d1aad9-de0e-4a60-a825-671b0e9f0c97.png)
![Uploading Screenshot_20220922-224720.png…]()

**Comment by efenatuyo** [comment]
Any errors

**Comment by vGaming4o** [comment]
![Uploading Screenshot_20220922-224720.png…]()

**Comment by vGaming4o** [comment]
> Any errors

![Uploading Screenshot_20220922-224720.png…]()

**Comment by vGaming4o** [comment]
> Any errors

![Screenshot_20220922-224720](https://user-images.githubusercontent.com/114186911/191838579-79fdcf49-dd5a-458e-9450-50036da649ec.png)

**Comment by vGaming4o** [comment]
> > Any errors
> 
> ![Screenshot_20220922-224720](https://user-images.githubusercontent.com/114186911/191838579-79fdcf49-dd5a-458e-9450-50036da649ec.png)

Can you help me to fix it?

**Comment by efenatuyo** [comment]
Try the new update 1.2.1

**Comment by vGaming4o** [comment]
> Try the new update 1.2.1

Ok
